enum ProductCategory {
  HOME,
  MAN,
  KID,
  PET,
  WOMEN,
  RESTAURANT,
  HEALTH,
  TECHNOLOGY,
  UNDEFINED
}
enum ProductSubCategory {
  BATHROOM,
  KITCHEN,
  DECORATION,
  ELECTRONIC_HOME,
  WOMEN,
  FURNITURE,
  PLANT,
  UNDEFINED
}

enum AdminStockType {
  ADMIN_STOCK_UNIQUE,
  ADMIN_STOCK_COLOR,
  ADMIN_STOCK_BY_SIZE,
  ADMIN_STOCK_BY_COLOR_SIZE,
  UNDEFINED
  
}

enum StockType { UNIQUE, BY_COLOR, BY_SIZE, BY_COLOR_SIZE, UNDEFINED }

enum PriceType {
  NORMAL,
  OFFERT,
  UNDEFINED
}

enum AdminColorType { YELLOW, BLUE, GREY, BLACK, RED, PINK }

enum Sizes { S, M, L, XL, XXL }

enum AvailableType { SHOP, HOME, SHOP_HOME, UNDEFINED }

enum DepartmentType { LIMA, ICA, AREQUIPA, LAMBAYEQUE, UNDEFINED }
enum ProvinceType { LIMA, NAZCA, AREQUIPA, CHICLAYO, UNDEFINED }

enum DistrictType {
  SANBORJA,
  SANISIDRO,
  SURQUILLO,
  SURCO,
  MOLINA,
  LINCE,
  JESUSMARIA,
  LIMA,
  ANCON,
  ATE,
  BARRANCO,
  BRENA,
  CARABAYLLO,
  COMAS,
  OLIVOS,
  LURIGANCHO,
  UNDEFINED
}

enum GroupedButtonsOrientation {
  HORIZONTAL,
  VERTICAL,
}
