name: service_products_business
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_keyboard_visibility: ^4.0.1
  font_awesome_flutter: ^8.10.0
  formz: ^0.3.2
  google_fonts: ^1.1.1
  image_picker: ^0.6.7+14
  pin_code_text_field: ^1.7.1
  responsive_screen: ^1.0.0
  shared_preferences: ^0.5.12+4
  socket_io_client: ^0.9.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
